import java.awt.Color;
import java.math.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xavier
 */
interface information
{
public void info();
}
interface waitingtime
{
public void fun1();
}



//class person implements information,waitingtime{

//public void info()

public class f1 extends javax.swing.JFrame {

    /**
     * Creates new form f1
     */
    public f1() {
        initComponents();
        c1.setEnabled(false);
        c2.setEnabled(false);
        c3.setEnabled(false);
        at1.setEnabled(false);
        at2.setEnabled(false);
        at3.setEnabled(false);
        t1.setEnabled(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
         ttime.setEnabled(false);
        wtime.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pur = new javax.swing.JTextField();
        len = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        land = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        di = new javax.swing.JTextField();
        ma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        b1 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ttime = new javax.swing.JTextField();
        wtime = new javax.swing.JTextField();
        at1 = new javax.swing.JTextField();
        at2 = new javax.swing.JTextField();
        at3 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(null);
        jPanel1.add(pur);
        pur.setBounds(417, 90, 127, 20);
        jPanel1.add(len);
        len.setBounds(417, 134, 127, 20);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("Measurement of cables");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 62, 250, 21);

        jLabel2.setText("No. of Landmarks :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(36, 297, 120, 20);

        land.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landActionPerformed(evt);
            }
        });
        jPanel1.add(land);
        land.setBounds(417, 292, 127, 20);

        jLabel3.setText("Purpose :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(51, 95, 60, 20);

        jLabel4.setText("Length :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(51, 139, 60, 20);

        jLabel5.setText("Distance :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(51, 183, 60, 20);

        jLabel6.setText("Material :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(51, 227, 60, 20);
        jPanel1.add(di);
        di.setBounds(417, 178, 127, 20);

        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });
        jPanel1.add(ma);
        ma.setBounds(417, 222, 127, 20);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel7.setText("Cabling Distribution ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 6, 490, 50);

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 560, 160, 60);

        a1.setText(" ");
        jPanel1.add(a1);
        a1.setBounds(30, 360, 75, 20);

        a2.setText(" ");
        jPanel1.add(a2);
        a2.setBounds(30, 400, 75, 20);

        a3.setText(" ");
        jPanel1.add(a3);
        a3.setBounds(30, 430, 75, 20);

        b1.setText(" ");
        jPanel1.add(b1);
        b1.setBounds(190, 360, 90, 20);

        b2.setText(" ");
        jPanel1.add(b2);
        b2.setBounds(190, 400, 90, 20);

        b3.setText(" ");
        jPanel1.add(b3);
        b3.setBounds(190, 430, 90, 20);

        jLabel8.setText("A Landmark");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 330, 70, 14);

        jLabel9.setText("B Landmark");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 330, 70, 20);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 560, 160, 60);

        jLabel10.setText("Average Waiting Time :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 520, 200, 14);

        jLabel12.setText("Average Turn Around Time :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 480, 200, 14);

        ttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttimeActionPerformed(evt);
            }
        });
        jPanel1.add(ttime);
        ttime.setBounds(280, 470, 180, 20);

        wtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtimeActionPerformed(evt);
            }
        });
        jPanel1.add(wtime);
        wtime.setBounds(280, 510, 180, 20);

        at1.setText(" ");
        jPanel1.add(at1);
        at1.setBounds(460, 360, 120, 20);

        at2.setText(" ");
        jPanel1.add(at2);
        at2.setBounds(460, 400, 120, 20);

        at3.setText(" ");
        jPanel1.add(at3);
        at3.setBounds(460, 430, 120, 20);

        c3.setText(" ");
        jPanel1.add(c3);
        c3.setBounds(340, 430, 100, 20);

        c2.setText(" ");
        jPanel1.add(c2);
        c2.setBounds(340, 400, 100, 20);

        c1.setText(" ");
        jPanel1.add(c1);
        c1.setBounds(340, 360, 110, 20);

        t3.setText(" ");
        jPanel1.add(t3);
        t3.setBounds(600, 430, 120, 20);

        t2.setText(" ");
        jPanel1.add(t2);
        t2.setBounds(600, 400, 120, 20);

        t1.setEditable(false);
        t1.setText(" ");
        jPanel1.add(t1);
        t1.setBounds(600, 360, 120, 20);

        jLabel11.setText("CompleteWork");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 330, 90, 20);

        jLabel13.setText("AverageDistance");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(470, 330, 110, 20);

        jLabel14.setText("TIMINGS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(610, 330, 60, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maActionPerformed

    private void landActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_landActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
        String purpose,mat;
        float dis,l;
        purpose=pur.getText();
        mat=ma.getText();
        dis=Float.parseFloat(di.getText());
        l=Float.parseFloat(len.getText());
        int n=Integer.parseInt(land.getText());
 // it takes pid of process

        int att1=0,att2=0,att3=0,btt1=0,btt2=0,btt3=0;
       
        //for (i=0;i<n;i++)
        purpose=pur.getText();
        mat=ma.getText();
        dis=Float.parseFloat(di.getText());
        l=Float.parseFloat(len.getText());
         n=Integer.parseInt(land.getText());
          
        //{

            //pid[i]= i+1;

            //	..System.out.println ("Landmark " +(i+1)+ " aTIMINGS:");

            //at[i]= sc.nextInt();
            //att1=Integer.parseInt(a1.getText());
            att1=Double.valueOf(a1.getText()).intValue();
            //att2=Integer.parseInt(a2.getText());
            att2=Double.valueOf(a2.getText()).intValue();
            //att3=Integer.parseInt(a3.getText());
            att3=Double.valueOf(a3.getText()).intValue();
            //btt1=Integer.parseInt(b1.getText());
            btt1=Double.valueOf(b1.getText()).intValue();
            //btt2=Integer.parseInt(b2.getText());
            btt2=Double.valueOf(b2.getText()).intValue();
            //btt3=Integer.parseInt(b3.getText());
            btt3=Double.valueOf(b3.getText()).intValue();            
//k[i]= bt[i];

            //f[i]= 0;

            // }

      /*  boolean a=true;
        while(true)
        {

            int min=999,c=n;

            if (tot==n)

            break;

            for ( i=0;i<n;i++)

            {

                if ((at[i]<=st) && (f[i]==0) && (bt[i]<min))

                {

                    min=bt[i];

                    c=i;

                }

            }

            if (c==n)

            st++;

            else

            {

                ct[c]=st+bt[c];
                st+=bt[c];
                ta[c]=ct[c]-at[c];
                wt[c]=ta[c]-bt[c];
                f[c]=1;
                tot++;

            }

        }

        lb.setText (("Landmark  aTIMINGS  bTIMINGS  COMPLETE AVG timings \n"));

        for(i=0;i<n;i++)

        {
            avgwt+= wt[i];

            avgta+= ta[i];

            lb.setText (pid[i] +"\t"+ at[i]+"\t"+ k[i] +"\t"+ ct[i] +"\t"+ ta[i] +"\t"+ wt[i]);

        }

        lb.setText ("\n average tat is "+ (float)(avgta/n));

        lb.setText ("average wt is "+ (float)(avgwt/n));
*/
      int ca,cb,cc,aa,ab,ac,taaa,tbbb,tccc;
      
      ca=att1+btt1; c1.setText(""+Math.abs(ca));
      cb=att2+btt2; c2.setText(""+Math.abs(cb));
      cc=att3+btt3; c3.setText(""+Math.abs(cc));
      aa=ca-att1;    at1.setText(""+Math.abs(aa));
      ab=ca-att2;    at2.setText(""+Math.abs(ab));
      ac=ca-att3;    at3.setText(""+Math.abs(ac));
      taaa=aa-btt1;  t1.setText(""+Math.abs(taaa)); 
      tbbb=aa-btt2;  t2.setText(""+Math.abs(tbbb));
      tccc=aa-btt3;  t3.setText(""+Math.abs(tccc));
      float taaat= (float)(aa+ab+ac)/3; ttime.setText(""+Math.abs(taaat));
     float waat=(float)(taaa+tbbb+tccc)/3; wtime.setText(""+Math.abs(waat));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("THANK YOU");
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wtimeActionPerformed

    private void ttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttimeActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        jPanel1.setBackground(Color.yellow);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField at1;
    private javax.swing.JTextField at2;
    private javax.swing.JTextField at3;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField di;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField land;
    private javax.swing.JTextField len;
    private javax.swing.JTextField ma;
    private javax.swing.JTextField pur;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField ttime;
    private javax.swing.JTextField wtime;
    // End of variables declaration//GEN-END:variables
}
